#!/bin/bash

# Get the fsf file from the command line argument.
FSF=$1
if [[ "$FSF" == "" ]]; then
        echo "I need a .fsf file to process, not submitting the job."
        echo "Try $ sub_feat /somepath/somefile.fsf"
        exit 1
fi
if [[ ! -f $FSF ]]; then
        echo "$FSF is not a file, giving up."
        exit 1
fi
if [[ "$FSF" != "/"* ]]; then
        echo "Converted local '$FSF' to absolute '$(pwd)/$FSF'"
        FSF=$(pwd)/$FSF
fi

# How many cores shall we allocate for this job?
# feat just uses 1 for now
CORES=4

# Write a new sbatch script

FSF_PATH="${FSF%/*}"
FSF_FILE="${FSF##*/}"
FSF_SHORT="${FSF_FILE%%.*}"
SCRIPT=${FSF_PATH}/${FSF_SHORT}.sbatch.sh

if [[ $FSF =~ (U[0-9]+) ]]; then
        SUB=${BASH_REMATCH[1]}
else
        SUB=_NA_
fi

echo "#!/bin/bash"                                          > "$SCRIPT"
echo "#SBATCH --job-name=feat${SUB: -4:4}_${CORES}"        >> "$SCRIPT"
echo "#SBATCH --nodes=1"                                   >> "$SCRIPT"
echo "#SBATCH --ntasks=1"                                  >> "$SCRIPT"
echo "#SBATCH --cpus-per-task=${CORES}"                    >> "$SCRIPT"
echo "#SBATCH --mem=2gb"                                   >> "$SCRIPT"
echo "#SBATCH --time=0"                                    >> "$SCRIPT"
echo "#SBATCH --export=ALL,OPENBLAS_NUM_THREADS=${CORES}"  >> "$SCRIPT"
echo "#SBATCH --output=${HOME}/slurmlogs/feat-%j.out"      >> "$SCRIPT"
echo "#SBATCH --error=${HOME}/slurmlogs/feat-%j.out"       >> "$SCRIPT"
echo ""                                                    >> "$SCRIPT"
echo "mkdir -p ~/slurmlogs"                                >> "$SCRIPT"
echo ""                                                    >> "$SCRIPT"
echo "echo Begin; date; hostname; pwd"                     >> "$SCRIPT"
echo ""                                                    >> "$SCRIPT"
echo "srun ${FSLDIR}/bin/feat ${FSF}"                      >> "$SCRIPT"
echo ""                                                    >> "$SCRIPT"
echo "echo End; date"                                      >> "$SCRIPT"
echo ""                                                    >> "$SCRIPT"

# Submit this script to slurm
sbatch -p fsl6 "${SCRIPT}"
