---
- name: Update and upgrade initial software packages
  hosts: "*"
  remote_user: aa
  become: yes
  become_method: sudo
  become_user: root
  tasks:

  - name: Upgrade base packages
    apt:
      update_cache: yes
      upgrade: full

  - name: Install jjm standard packages
    apt:
      pkg: 
        - build-essential
        - ca-certificates
        - curl
        - wget
        - lsb-release
        - gnupg
        - vim
        - tree
        - htop
        - sshpass
        - ansible
        - whois
        - zip
        - unzip
        - nfs-kernel-server
        - nfs-common
        - cifs-utils
        - python2
        - python3
        - python3-pip
        - python3-distutils
        - default-jre
        - tmux
        - reptyr
        - git

