---
- name: Set timezone to Americas/New_York
  hosts: "*"
  remote_user: aa
  become: yes
  become_method: sudo
  become_user: root
  tasks:

  - name: Set timezone
    timezone:
      name: America/New_York

